### ISSUE TITLE
not enough arguments in call to registerPackageData in chapter 3 - pkgregister_test.go

### ISSUE THREAD

**Issue by rikyhidayat21** [amitsaha/golang-web-app-recipes#13]
In the book Practical Go chapter 3 - pkgregister-data/pkgregister_test.go, we only give single parameters for this code:
```go
func TestRegisterPackageData(t *testing.T) {
  // ...
  pResult, err := registerPackageData(ts.URL)
  // ...
}
```
It will throw an error when running the test because of `not enough arguments in call to registerPackageData`.
```shell
# github.com/rikyhidayat21/pkgregister-data [github.com/rikyhidayat21/pkgregister-data.test]
/Users/riky/Dev/learning-go/goprac/ch3/pkgregister-data/pkgregister_test.go:55:38: not enough arguments in call to registerPackageData
	have (string)
	want (*http.Client, string, pkgData)
FAIL	github.com/rikyhidayat21/pkgregister-data [build failed]
FAIL
```

The solution we need to add appropriate parameters as it is.
It should be like this:
```go
func TestRegisterPackageData(t *testing.T) {
  // ...
  pResult, err := registerPackageData(createHTTPClientWithTimeout(1000), ts.URL, p)
  // ...
}
```
Then if we run the test, now it will be pass.

**Comment by amitsaha** [comment]
thank you @rikyhidayat21 for reporting the issue. I have [updated the website](https://github.com/practicalgo/website/commit/4e5071ede312aedd2176ffec900e9d810cc5297a). 

The published code was already the correct version thankfully!
